#server
server:
  port: 10000
  servlet:
    session:
      tracking-modes: cookie


#MyBatis
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/post?serverTimezone=Asia/Seoul
    username: root
    password: 1234

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
