#server
server:
  port: 10000
  servlet:
    session:
      tracking-modes: cookie


# datasource - MySQL
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/post?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.post.domain.vo
  configuration:
    map-underscore-to-camel-case: true
